### PR TITLE
Add scavenging manifests

### PR DESCRIPTION
**Pull request by oldskool**
#### PR Checklist
- [x] Chart Version bumped
- [x] Chart packaged and index updated (you can use `./release`)
- [x] CHANGELOG.md updated
- [x] Variables and other changes are documented in the README.md

**What this PR does / why we need it**:
Adds several manifests in order to allow for scheduled [scavenging](https://eventstore.org/docs/server/scavenging/) jobs to take place. The job creates a pod based on the `lachlanevenson/k8s-kubectl:latest` image, gets all the eventstore pods from the release and sends a POST request to them asking them to scavenge. It looks a little something like this (actual local Minikube test results):

```
$ kubectl create job scavenging-test --from=cronjob/eventstore-scavenging
job.batch/scavenging-test created

$ kubectl get job
NAME              DESIRED   SUCCESSFUL   AGE
scavenging-test   1         0            3s

$ kubectl logs scavenging-test-l5tld 
[Thu Feb 28 17:38:37 UTC 2019] Start instructing all nodes to scavenge
[Thu Feb 28 17:38:38 UTC 2019] Instructing node eventstore-0 to scavenge
HTTP/1.1 200 OK
Access-Control-Allow-Methods: POST, OPTIONS
Access-Control-Allow-Headers: Content-Type, X-Requested-With, X-Forwarded-Host, X-Forwarded-Prefix, X-PINGOTHER, Authorization, ES-LongPoll, ES-ExpectedVersion, ES-EventId, ES-EventType, ES-RequiresMaster, ES-HardDelete, ES-ResolveLinkTos
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, ES-Position, ES-CurrentVersion
Content-Type: text/plain; charset=utf-8
Server: Mono-HTTPAPI/1.0
Date: Thu, 28 Feb 2019 17:38:39 GMT
Content-Length: 42
Keep-Alive: timeout=15,max=100

EventStore.Core.Messages.ScavengeResultDto[Thu Feb 28 17:38:39 UTC 2019] Instructing node eventstore-1 to scavenge
HTTP/1.1 200 OK
Access-Control-Allow-Methods: POST, OPTIONS
Access-Control-Allow-Headers: Content-Type, X-Requested-With, X-Forwarded-Host, X-Forwarded-Prefix, X-PINGOTHER, Authorization, ES-LongPoll, ES-ExpectedVersion, ES-EventId, ES-EventType, ES-RequiresMaster, ES-HardDelete, ES-ResolveLinkTos
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, ES-Position, ES-CurrentVersion
Content-Type: text/plain; charset=utf-8
Server: Mono-HTTPAPI/1.0
Date: Thu, 28 Feb 2019 17:38:39 GMT
Content-Length: 42
Keep-Alive: timeout=15,max=100

EventStore.Core.Messages.ScavengeResultDto[Thu Feb 28 17:38:39 UTC 2019] Instructing node eventstore-2 to scavenge
HTTP/1.1 200 OK
Access-Control-Allow-Methods: POST, OPTIONS
Access-Control-Allow-Headers: Content-Type, X-Requested-With, X-Forwarded-Host, X-Forwarded-Prefix, X-PINGOTHER, Authorization, ES-LongPoll, ES-ExpectedVersion, ES-EventId, ES-EventType, ES-RequiresMaster, ES-HardDelete, ES-ResolveLinkTos
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, ES-Position, ES-CurrentVersion
Content-Type: text/plain; charset=utf-8
Server: Mono-HTTPAPI/1.0
Date: Thu, 28 Feb 2019 17:38:40 GMT
Content-Length: 42
Keep-Alive: timeout=15,max=100

EventStore.Core.Messages.ScavengeResultDto[Thu Feb 28 17:38:40 UTC 2019] Instructing node eventstore-3 to scavenge
HTTP/1.1 200 OK
Access-Control-Allow-Methods: POST, OPTIONS
Access-Control-Allow-Headers: Content-Type, X-Requested-With, X-Forwarded-Host, X-Forwarded-Prefix, X-PINGOTHER, Authorization, ES-LongPoll, ES-ExpectedVersion, ES-EventId, ES-EventType, ES-RequiresMaster, ES-HardDelete, ES-ResolveLinkTos
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, ES-Position, ES-CurrentVersion
Content-Type: text/plain; charset=utf-8
Server: Mono-HTTPAPI/1.0
Date: Thu, 28 Feb 2019 17:38:41 GMT
Content-Length: 42
Keep-Alive: timeout=15,max=100

EventStore.Core.Messages.ScavengeResultDto[Thu Feb 28 17:38:41 UTC 2019] Instructed all nodes to scavenge
```

This allows the user to run automated scavenging jobs (defaults to every day at 2:00 AM, but this is configurable). The default settings will prevent the scavenging manifests from being deployed, so this change is backwards compatible with earlier releases of the chart without adding anything to the users' cluster.

### CODE REVIEW

**Comment by riccardone** [comment]
This PR looks good. I need a bit more time for testing. Can you please confirm if the scavenge operation run in parallel or in sequence on all the cluster nodes

**Comment by oldskool** [comment]
@riccardone No problem. Once the POST has been dispatched to all nodes, they will run the scavenging operations in parallel. The POST just queues the scavenge job on that node and it will keep running in the background. This is fully managed by EventStore itself. You can also see/follow the scavenge jobs through the Web UI and HTTP API:

screen shot 2019-03-01 at 15 08 13

**Comment by gregoryyoung** [comment]
Running scavenge on all nodes concurrently would be an unusual case (eg you have traffic 0800-2000 then none during the evening). Usually you would want to do them one by one.

**Comment by oldskool** [comment]
@gregoryyoung What would be the downside of doing it concurrently? And thus would it be better to be able to schedule them per ES node?

**Pull request merged**
